SRC_DIR := $(CURDIR)/../src
SRAM_V := $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_sram/verilog
BUILD := sim_build/bscan
.PHONY: all clean
all: $(BUILD)/bscan.vvp
	vvp $(BUILD)/bscan.vvp
$(BUILD)/bscan.vvp: tb_bscan.v $(SRC_DIR)/zirh3_top.v $(wildcard $(SRC_DIR)/zirh_*.v)
	mkdir -p $(BUILD)
	iverilog -g2012 -DZIRH_SIM_ENV -DFUNCTIONAL -I$(SRC_DIR) \
	  -Pzirh3_top.ROM_HEX=\"$(PWD)/../fw/rom.hex\" \
	  -s tb_bscan -o $@ tb_bscan.v \
	  $(SRAM_V)/RM_IHPSG13_1P_core_behavioral_bm_bist.v \
	  $(SRAM_V)/RM_IHPSG13_1P_1024x8_c2_bm_bist.v \
	  $(SRAM_V)/RM_IHPSG13_1P_4096x8_c3_bm_bist.v \
	  $(SRC_DIR)/vex/VexRiscv_Lite.v $(SRC_DIR)/zirh_vex_wrap.v \
	  $(SRC_DIR)/zirh_tmr_lib.v $(SRC_DIR)/zirh_rom.v $(SRC_DIR)/zirh_bus.v \
	  $(SRC_DIR)/zirh_ecc_ram.v $(SRC_DIR)/zirh_rs422.v \
	  $(SRC_DIR)/zirh_uart_regs.v $(SRC_DIR)/zirh_soc.v \
	  $(SRC_DIR)/zirh_boot_ctrl.v $(SRC_DIR)/zirh_isp_rx.v \
	  $(SRC_DIR)/zirh_jtag_dm.v $(SRC_DIR)/zirh_dbg_gate.v \
	  $(SRC_DIR)/zirh_clkobs.v $(SRC_DIR)/zirh_por_ro.v \
	  $(SRC_DIR)/zirh_sram_bist.v $(SRC_DIR)/zirh_sram39.v \
	  $(SRC_DIR)/zirh_tmr_ff32.v $(SRC_DIR)/zirh_hk.v $(SRC_DIR)/zirh_tlm2.v \
	  $(SRC_DIR)/zirh_mbist.v $(SRC_DIR)/zirh_gpio.v $(SRC_DIR)/zirh_timer.v $(SRC_DIR)/zirh_i2c.v $(SRC_DIR)/zirh_bank64.v \
	  $(SRC_DIR)/zirh3_top.v
clean:
	rm -rf $(BUILD)
