# ZIRH - clock-loss observer unit suite
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src

SIM_BUILD = sim_build/clkobs

COMPILE_ARGS += -I$(SRC_DIR)
VERILOG_SOURCES += $(SRC_DIR)/zirh_tmr_lib.v
VERILOG_SOURCES += $(SRC_DIR)/zirh_clkobs.v

TOPLEVEL = zirh_clkobs
COCOTB_TEST_MODULES = test_clkobs

include $(shell cocotb-config --makefiles)/Makefile.sim
