# ZIRH P2 - march/BIST engine suite (over the full sram39 + macros)
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
SRAM_V = $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_sram/verilog

SIM_BUILD = sim_build/bist

COMPILE_ARGS += -DFUNCTIONAL
COMPILE_ARGS += -I$(SRC_DIR)
COMPILE_ARGS += -DZIRH_ASSERTIONS
VERILOG_SOURCES += $(SRC_DIR)/zirh_tmr_lib.v
VERILOG_SOURCES += $(SRAM_V)/RM_IHPSG13_1P_core_behavioral_bm_bist.v
VERILOG_SOURCES += $(SRAM_V)/RM_IHPSG13_1P_1024x8_c2_bm_bist.v
VERILOG_SOURCES += $(SRC_DIR)/zirh_sram_bist.v
VERILOG_SOURCES += $(SRC_DIR)/zirh_sram39.v

TOPLEVEL = zirh_sram39
COCOTB_TEST_MODULES = test_bist

include $(shell cocotb-config --makefiles)/Makefile.sim
