# ZIRH-3 - memsys integration smoke
SRC_DIR := $(CURDIR)/../src
SRAM_V := $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_sram/verilog
BUILD := sim_build/memsys
.PHONY: all clean
all: $(BUILD)/memsys.vvp
	vvp $(BUILD)/memsys.vvp
$(BUILD)/memsys.vvp: tb_memsys.v $(SRC_DIR)/zirh3_memsys.v
	mkdir -p $(BUILD)
	iverilog -g2012 -DZIRH_SIM_ENV -DFUNCTIONAL -I$(SRC_DIR) \
	  -s tb_memsys -o $@ tb_memsys.v \
	  $(SRAM_V)/RM_IHPSG13_1P_core_behavioral_bm_bist.v \
	  $(SRAM_V)/RM_IHPSG13_1P_1024x8_c2_bm_bist.v \
	  $(SRC_DIR)/zirh_tmr_lib.v $(SRC_DIR)/zirh_sram_bist.v \
	  $(SRC_DIR)/zirh_sram39.v $(SRC_DIR)/zirh_boot_ctrl.v \
	  $(SRC_DIR)/zirh_qspi.v $(SRC_DIR)/zirh_clkobs.v \
	  $(SRC_DIR)/zirh_dbg_gate.v $(SRC_DIR)/zirh3_memsys.v
clean:
	rm -rf $(BUILD)
