# ZIRH-3 - SPI master block suite (Cycle 32)
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
SIM_BUILD = sim_build/spi

VERILOG_SOURCES += $(SRC_DIR)/zirh_tmr_lib.v
VERILOG_SOURCES += $(SRC_DIR)/zirh_fifo.v
VERILOG_SOURCES += $(SRC_DIR)/zirh_spi.v

TOPLEVEL = zirh_spi
COCOTB_TEST_MODULES = test_spi

COMPILE_ARGS += -I$(SRC_DIR)
COMPILE_ARGS += -DZIRH_SIM_ENV

include $(shell cocotb-config --makefiles)/Makefile.sim
