SRC_DIR := $(CURDIR)/../src
BUILD := sim_build/vex
.PHONY: all clean
all: $(BUILD)/vex.vvp
	vvp $(BUILD)/vex.vvp
$(BUILD)/vex.vvp: tb_vex.v $(SRC_DIR)/zirh_vex_wrap.v $(SRC_DIR)/vex/VexRiscv_Lite.v
	mkdir -p $(BUILD)
	iverilog -g2012 -s tb_vex -o $@ tb_vex.v \
	  $(SRC_DIR)/zirh_vex_wrap.v \
	  $(SRC_DIR)/vex/VexRiscv_Lite.v
clean:
	rm -rf $(BUILD)
