SRC_DIR := $(CURDIR)/../src
SRAM_V := $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_sram/verilog
BUILD := sim_build/die
.PHONY: all clean
all: $(BUILD)/die.vvp
	vvp $(BUILD)/die.vvp
$(BUILD)/die.vvp: tb_die.v $(SRC_DIR)/zirh3_die.v
	mkdir -p $(BUILD)
	iverilog -g2012 -DZIRH_SIM_ENV -DFUNCTIONAL -I$(SRC_DIR) \
	  -s tb_die -o $@ tb_die.v \
	  $(SRAM_V)/RM_IHPSG13_1P_core_behavioral_bm_bist.v \
	  $(SRAM_V)/RM_IHPSG13_1P_1024x8_c2_bm_bist.v \
	  $(SRC_DIR)/zirh_tmr_lib.v $(SRC_DIR)/zirh_sram_bist.v \
	  $(SRC_DIR)/zirh_sram39.v $(SRC_DIR)/zirh_boot_ctrl.v \
	  $(SRC_DIR)/zirh_qspi.v $(SRC_DIR)/zirh_clkobs.v \
	  $(SRC_DIR)/zirh_dbg_gate.v $(SRC_DIR)/zirh_por_ro.v \
	  $(SRC_DIR)/zirh_isp_rx.v \
	  $(SRC_DIR)/zirh3_memsys.v $(SRC_DIR)/zirh3_die.v
clean:
	rm -rf $(BUILD)
