# =============================================================================
# ZIRH-3 - equivalence cell library generator (Cycle 28)
#
# The PDK's simulation cells drive their outputs through UDP tables,
# which no open formal front end reads. The liberty file, however,
# states every combinational cell's FUNCTION as a boolean expression -
# so the equivalence library is generated from the liberty, not
# hand-written: nothing to drift, nothing to trust but the PDK's own
# function attributes. Sequential cells are the exception (liberty
# states them as ff groups); dfrbpq gets an explicit model below.
#
#   python3 formal_eqlib.py <liberty> <out.v> <cell> [<cell> ...]
# =============================================================================

import re
import sys


def liberty_cell_functions(text, cell):
    i = text.index(f"cell ({cell})")
    j = text.find("\n  cell (", i + 10)
    if j == -1:
        j = len(text)
    body = text[i:j]
    pins, funcs = [], {}
    for m in re.finditer(
            r'pin \((\w+)\)\s*\{(.*?)\n    \}', body, re.S):
        name, pbody = m.group(1), m.group(2)
        direction = re.search(r'direction\s*:\s*"?(\w+)"?', pbody).group(1)
        f = re.search(r'function\s*:\s*"([^"]+)"', pbody)
        pins.append((name, direction))
        if f and direction == "output":
            funcs[name] = f.group(1)
    return pins, funcs


def to_verilog(expr):
    # liberty booleans: * = and, + = or, ! = not, ^ = xor
    return expr.replace("*", " & ").replace("+", " | ").replace("!", "~")


DFRBP = """
module sg13g2_dfrbp_1 (input wire CLK, input wire D,
                       input wire RESET_B,
                       output reg Q, output wire Q_N);
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 1'b0;
    else          Q <= D;
  assign Q_N = ~Q;
endmodule
"""

DFRBPQ = """
module sg13g2_dfrbpq_1 (input wire CLK, input wire D,
                        input wire RESET_B, output reg Q);
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 1'b0;
    else          Q <= D;
endmodule
"""

TIES = """
module sg13g2_tielo (output wire L_LO);
  assign L_LO = 1'b0;
endmodule
module sg13g2_tiehi (output wire L_HI);
  assign L_HI = 1'b1;
endmodule
"""


def main(lib_path, out_path, cells):
    text = open(lib_path).read()
    out = ["// GENERATED by formal_eqlib.py from the PDK liberty - do not edit"]
    for cell in cells:
        if cell in ("sg13g2_dfrbpq_1", "sg13g2_dfrbp_1",
                    "sg13g2_tielo", "sg13g2_tiehi"):
            continue
        pins, funcs = liberty_cell_functions(text, cell)
        outs = [n for n, d in pins if d == "output"]
        if outs and not funcs:
            print(f"ERROR: no function for {cell}", file=sys.stderr)
            return 1
        ports = ", ".join(
            f"{'output' if d == 'output' else 'input'} wire {n}"
            for n, d in pins)
        out.append(f"module {cell} ({ports});")
        for pin, f in funcs.items():
            out.append(f"  assign {pin} = {to_verilog(f)};")
        out.append("endmodule")
    out.append(DFRBP)
    out.append(DFRBPQ)
    out.append(TIES)
    open(out_path, "w").write("\n".join(out) + "\n")
    print(f"eqlib: {len(cells)} cells into {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], sys.argv[2], sys.argv[3:]))
